version: 2.1

orbs:
  node: circleci/node@4.6.0

executors:
  node:
    docker:
      - image: cimg/node:current


jobs:
  install_dependencies:
    executor: node
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          cache-path: node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: yarn test
  deploy:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run: mkdir -p ~/.ssh      
      - run: ssh-keyscan github.com >> ~/.ssh/known_hosts    
      - add_ssh_keys:
          fingerprints:
            - "ca:b5:0f:98:65:d1:a2:b3:58:2a:44:8a:b5:7c:bf:d1"
      - run:
          name: Git config email
          command: git config --global user.email "circleci@circleci.com"
      - run:
          name: Git config name
          command: git config --global user.name "Circle CI"
      - run:
          name: Deploy
          command: yarn deploy

workflows:
  install_dependencies_and_test:
    jobs:
      - install_dependencies
      - test:
          requires:
            - install_dependencies
      - deploy:
          filters:
            branches:
              only:
                - main 
          requires:
            - test

