version: 2.1

orbs:
  node: circleci/node@4.6.0


jobs:
  build:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          cache-path: node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker:
      - image: cimg/node:current
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: yarn test

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
